
#########################
# Set detector parameters
#
/AdEPTSim/Image/SNR 5
/AdEPTSim/Image/NoiseCenter 0
/AdEPTSim/Image/NoiseSigma 0

#/control/alias initialValue 0
#/control/alias   finalValue 10
#/control/alias     stepSize 1
#/control/loop runProton.mac counterName {initialValue} {finalValue} {stepSize}

/control/alias initialValue 0
/control/alias   finalValue 10
/control/alias     stepSize 1
/control/loop runGamma.mac counterName {initialValue} {finalValue} {stepSize}
